# -*- coding: utf-8 -*-
"""2020-10-12

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LByl0zJlT2dgDKSTPKZvZRODQANM_bSU
"""

import sys
T = int(sys.stdin.readline())

for i in range(T):
    a, b = map(int, sys.stdin.readline().split())
    print(a+b)

h, m = map(int, input().split())
if m >= 45:
  print(h, m-45)
elif m < 45 and h > 0:
  print(h-1, m+15)
else:
  print(23, m+15)

n = int(input())
ans = 0
for i in range(1,n+1):
  ans += i
print(ans)

n = int(input())
for i in range(n,0,-1):
  print(i)

T = int(input())
i = 0
for i in range(T):
  i += 1
  a, b = map(int, input().split())
  print("Case #%d: %d" %(i,a+b))

import sys
read = sys.stdin.readline
T = int(read())
for i in range(T):
  test = [int(x) for x in read().split()]
  print("Case #{}: {}".format(i+1, test[0]+test[1]))